# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 421)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 71, 51))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/today.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 80, 71, 51))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 200, 71, 51))
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 260, 71, 51))
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 320, 71, 51))
        self.pushButton_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/themes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(120, 10, 651, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 100, 581, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(470, 30, 91, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(300, 40, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(380, 40, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(300, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(380, 20, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_18.setGeometry(QtCore.QRect(20, 40, 131, 21))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_25.setGeometry(QtCore.QRect(160, 40, 121, 21))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab)
        self.pushButton_26.setGeometry(QtCore.QRect(270, 310, 81, 31))
        self.pushButton_26.setObjectName("pushButton_26")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(30, 10, 531, 321))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 521, 251))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(7)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(6, item)
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_29.setGeometry(QtCore.QRect(240, 260, 81, 31))
        self.pushButton_29.setObjectName("pushButton_29")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(20, 50, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 100, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_6.setGeometry(QtCore.QRect(350, 200, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(350, 30, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(350, 80, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(350, 130, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(350, 180, 47, 13))
        self.label_9.setObjectName("label_9")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_3.setGeometry(QtCore.QRect(350, 150, 111, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_8.setGeometry(QtCore.QRect(360, 240, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_9.setGeometry(QtCore.QRect(350, 50, 111, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_5)
        self.comboBox_10.setGeometry(QtCore.QRect(350, 100, 111, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 150, 231, 131))
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_10 = QtWidgets.QLabel(self.tab_6)
        self.label_10.setGeometry(QtCore.QRect(20, 0, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_6)
        self.label_11.setGeometry(QtCore.QRect(350, 80, 61, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_6)
        self.label_12.setGeometry(QtCore.QRect(20, 80, 61, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 100, 113, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_13 = QtWidgets.QLabel(self.tab_6)
        self.label_13.setGeometry(QtCore.QRect(350, 180, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setGeometry(QtCore.QRect(350, 130, 47, 13))
        self.label_14.setObjectName("label_14")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(20, 20, 113, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setGeometry(QtCore.QRect(350, 30, 47, 13))
        self.label_15.setObjectName("label_15")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(350, 200, 113, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(20, 130, 71, 16))
        self.label_16.setObjectName("label_16")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_4.setGeometry(QtCore.QRect(350, 150, 111, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 10, 81, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(270, 240, 111, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setGeometry(QtCore.QRect(400, 240, 111, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(20, 40, 61, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_22.setGeometry(QtCore.QRect(20, 60, 113, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.comboBox_11 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_11.setGeometry(QtCore.QRect(350, 50, 111, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_12 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_12.setGeometry(QtCore.QRect(350, 100, 111, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 150, 191, 121))
        self.textEdit_3.setObjectName("textEdit_3")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_8)
        self.tabWidget_4.setGeometry(QtCore.QRect(10, 10, 531, 281))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_9)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 521, 291))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tabWidget_4.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_3.setGeometry(QtCore.QRect(230, 30, 113, 20))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_24 = QtWidgets.QLabel(self.tab_10)
        self.label_24.setGeometry(QtCore.QRect(150, 30, 81, 20))
        self.label_24.setObjectName("label_24")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_19.setGeometry(QtCore.QRect(240, 170, 91, 31))
        self.pushButton_19.setObjectName("pushButton_19")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_4.setGeometry(QtCore.QRect(230, 80, 113, 20))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_29 = QtWidgets.QLabel(self.tab_10)
        self.label_29.setGeometry(QtCore.QRect(150, 80, 81, 20))
        self.label_29.setObjectName("label_29")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_5.setGeometry(QtCore.QRect(230, 130, 113, 20))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_30 = QtWidgets.QLabel(self.tab_10)
        self.label_30.setGeometry(QtCore.QRect(130, 130, 91, 20))
        self.label_30.setObjectName("label_30")
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.label_35 = QtWidgets.QLabel(self.tab_11)
        self.label_35.setGeometry(QtCore.QRect(20, 0, 61, 16))
        self.label_35.setObjectName("label_35")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_16.setGeometry(QtCore.QRect(20, 20, 113, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_21.setGeometry(QtCore.QRect(170, 220, 111, 41))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_22.setGeometry(QtCore.QRect(290, 220, 111, 41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_27.setGeometry(QtCore.QRect(170, 20, 71, 21))
        self.pushButton_27.setObjectName("pushButton_27")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_10.setGeometry(QtCore.QRect(260, 70, 113, 20))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_31 = QtWidgets.QLabel(self.tab_11)
        self.label_31.setGeometry(QtCore.QRect(180, 120, 81, 20))
        self.label_31.setObjectName("label_31")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_15.setGeometry(QtCore.QRect(260, 170, 113, 20))
        self.lineEdit_15.setText("")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_32 = QtWidgets.QLabel(self.tab_11)
        self.label_32.setGeometry(QtCore.QRect(180, 70, 81, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab_11)
        self.label_33.setGeometry(QtCore.QRect(160, 170, 91, 20))
        self.label_33.setObjectName("label_33")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_17.setGeometry(QtCore.QRect(260, 120, 113, 20))
        self.lineEdit_17.setText("")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.tabWidget_4.addTab(self.tab_11, "")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_28.setGeometry(QtCore.QRect(260, 300, 81, 31))
        self.pushButton_28.setObjectName("pushButton_28")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 251, 311))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_11.setGeometry(QtCore.QRect(60, 60, 113, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_12.setGeometry(QtCore.QRect(60, 110, 113, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_13.setGeometry(QtCore.QRect(60, 160, 113, 20))
        self.lineEdit_13.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_14.setGeometry(QtCore.QRect(60, 210, 113, 20))
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 270, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(60, 40, 61, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setGeometry(QtCore.QRect(60, 90, 47, 13))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(60, 140, 61, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(60, 190, 101, 16))
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(40, 240, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 20, 251, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_23.setGeometry(QtCore.QRect(70, 60, 111, 20))
        self.lineEdit_23.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_24.setGeometry(QtCore.QRect(70, 20, 111, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_14.setGeometry(QtCore.QRect(90, 90, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 159, 251, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_47.setGeometry(QtCore.QRect(80, 70, 113, 20))
        self.lineEdit_47.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_45.setGeometry(QtCore.QRect(80, 10, 113, 20))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_23.setGeometry(QtCore.QRect(100, 140, 75, 23))
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_46.setGeometry(QtCore.QRect(80, 40, 113, 20))
        self.lineEdit_46.setText("")
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_48.setGeometry(QtCore.QRect(80, 100, 113, 20))
        self.lineEdit_48.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(80, 120, 111, 20))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_3.setGeometry(QtCore.QRect(20, 10, 561, 331))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_13)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 100, 531, 191))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(1)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_13)
        self.pushButton_13.setGeometry(QtCore.QRect(310, 30, 121, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_13)
        self.lineEdit_19.setGeometry(QtCore.QRect(140, 40, 131, 21))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_25 = QtWidgets.QLabel(self.tab_13)
        self.label_25.setGeometry(QtCore.QRect(40, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_14)
        self.pushButton_24.setGeometry(QtCore.QRect(310, 30, 121, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        self.label_26 = QtWidgets.QLabel(self.tab_14)
        self.label_26.setGeometry(QtCore.QRect(40, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_14)
        self.lineEdit_20.setGeometry(QtCore.QRect(140, 40, 131, 21))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_14)
        self.tableWidget_4.setGeometry(QtCore.QRect(10, 100, 531, 191))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(1)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        self.tabWidget_3.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_25.setGeometry(QtCore.QRect(310, 30, 121, 31))
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_27 = QtWidgets.QLabel(self.tab_15)
        self.label_27.setGeometry(QtCore.QRect(40, 40, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_15)
        self.lineEdit_21.setGeometry(QtCore.QRect(140, 40, 131, 21))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_15)
        self.tableWidget_5.setGeometry(QtCore.QRect(10, 100, 531, 191))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(1)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        self.tabWidget_3.addTab(self.tab_15, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox3.setEnabled(True)
        self.groupBox3.setGeometry(QtCore.QRect(560, 0, 221, 371))
        self.groupBox3.setStyleSheet("")
        self.groupBox3.setTitle("")
        self.groupBox3.setObjectName("groupBox3")
        self.label_21 = QtWidgets.QLabel(self.groupBox3)
        self.label_21.setEnabled(True)
        self.label_21.setGeometry(QtCore.QRect(50, 50, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 120, 71, 71))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton_15.setGeometry(QtCore.QRect(120, 120, 71, 71))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 200, 71, 71))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton_17.setGeometry(QtCore.QRect(120, 200, 71, 71))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox3)
        self.pushButton_18.setGeometry(QtCore.QRect(100, 330, 21, 23))
        self.pushButton_18.setFlat(False)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(30, 140, 71, 51))
        self.pushButton_20.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/Client.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_20.setIcon(icon5)
        self.pushButton_20.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_20.setObjectName("pushButton_20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "To"))
        self.pushButton_6.setText(_translate("MainWindow", "Add"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Rent"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Retrieve"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.label.setText(_translate("MainWindow", "Type"))
        self.label_2.setText(_translate("MainWindow", "Days"))
        self.lineEdit_18.setPlaceholderText(_translate("MainWindow", "Enter Book Title"))
        self.lineEdit_25.setPlaceholderText(_translate("MainWindow", "Enter Client Username"))
        self.pushButton_26.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book Name"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Description"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Code"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Book Price"))
        item = self.tableWidget_6.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Book Author"))
        item = self.tableWidget_6.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Book Publisher"))
        item = self.tableWidget_6.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Book Category"))
        self.pushButton_29.setText(_translate("MainWindow", "Export"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "All Books"))
        self.label_3.setText(_translate("MainWindow", "Book Title"))
        self.label_4.setText(_translate("MainWindow", "Description"))
        self.label_5.setText(_translate("MainWindow", "Book Code"))
        self.label_6.setText(_translate("MainWindow", "Author"))
        self.label_7.setText(_translate("MainWindow", "Publisher"))
        self.label_8.setText(_translate("MainWindow", "Category"))
        self.label_9.setText(_translate("MainWindow", "Price"))
        self.pushButton_8.setText(_translate("MainWindow", "Save"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Add Book"))
        self.label_10.setText(_translate("MainWindow", "Book Title"))
        self.label_11.setText(_translate("MainWindow", "Publisher"))
        self.label_12.setText(_translate("MainWindow", "Book Code"))
        self.label_13.setText(_translate("MainWindow", "Price"))
        self.label_14.setText(_translate("MainWindow", "Category"))
        self.label_15.setText(_translate("MainWindow", "Author"))
        self.label_16.setText(_translate("MainWindow", "Description"))
        self.pushButton_7.setText(_translate("MainWindow", "Search"))
        self.pushButton_9.setText(_translate("MainWindow", "Delete"))
        self.pushButton_10.setText(_translate("MainWindow", "Save"))
        self.label_28.setText(_translate("MainWindow", "Book Title"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Edit/Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Email Id"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Client National Id"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_9), _translate("MainWindow", "All Clients"))
        self.label_24.setText(_translate("MainWindow", "Client Name"))
        self.pushButton_19.setText(_translate("MainWindow", "Add Client"))
        self.label_29.setText(_translate("MainWindow", "Client Email"))
        self.label_30.setText(_translate("MainWindow", "Client National Id"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("MainWindow", "Add Client"))
        self.label_35.setText(_translate("MainWindow", "Client Name"))
        self.pushButton_21.setText(_translate("MainWindow", "Delete"))
        self.pushButton_22.setText(_translate("MainWindow", "Save"))
        self.pushButton_27.setText(_translate("MainWindow", "Search"))
        self.label_31.setText(_translate("MainWindow", "Client Email"))
        self.label_32.setText(_translate("MainWindow", "Client Name"))
        self.label_33.setText(_translate("MainWindow", "Client National Id"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "Edit/Delete Client"))
        self.pushButton_28.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Page"))
        self.groupBox.setTitle(_translate("MainWindow", "Add New User"))
        self.pushButton_11.setText(_translate("MainWindow", "Sign Up!"))
        self.label_17.setText(_translate("MainWindow", "Username"))
        self.label_18.setText(_translate("MainWindow", "Email Id"))
        self.label_19.setText(_translate("MainWindow", "Password"))
        self.label_20.setText(_translate("MainWindow", "Confirm Password"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Login User"))
        self.lineEdit_23.setPlaceholderText(_translate("MainWindow", "password"))
        self.lineEdit_24.setPlaceholderText(_translate("MainWindow", "username"))
        self.pushButton_14.setText(_translate("MainWindow", "Login"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Edit User Info"))
        self.lineEdit_47.setPlaceholderText(_translate("MainWindow", "Edit User Password"))
        self.lineEdit_45.setPlaceholderText(_translate("MainWindow", "Edit Username"))
        self.pushButton_23.setText(_translate("MainWindow", "Save Edits"))
        self.lineEdit_46.setPlaceholderText(_translate("MainWindow", "Edit Email"))
        self.lineEdit_48.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Page"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Categories"))
        self.pushButton_13.setText(_translate("MainWindow", "Add New Category"))
        self.label_25.setText(_translate("MainWindow", "New Category"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("MainWindow", "Category"))
        self.pushButton_24.setText(_translate("MainWindow", "Add New Author"))
        self.label_26.setText(_translate("MainWindow", "New Author"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Author"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_14), _translate("MainWindow", "Author"))
        self.pushButton_25.setText(_translate("MainWindow", "Add New Publisher"))
        self.label_27.setText(_translate("MainWindow", "New Publisher"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Publishers"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_15), _translate("MainWindow", "Publisher"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.label_21.setText(_translate("MainWindow", "Apply New Theme"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_17.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_18.setText(_translate("MainWindow", "X"))
import icons_rc
